Length units
KittyCAD/modeling-api pull request #131
Opened 2024-02-19 02:12 UTC by jessfraz

to catch you up @adamchalmers (and im happy to go over on a call) this PR https://github.com/KittyCAD/engine/pull/1780 means the engine assumes all units are mm. The easiest way for us to then use kcl with units, in the current setup without having to change both the client side js to be unit aware, and the executor to be unit aware, is to change the rust actor to be unit aware and convert right before sending to the engine to mm.

So assume we have a modeling command we fire right at start of engine: 
```SetUnits{units: UnitLength}``` we can also call this when the user changes their settings. regardless it changes the units in the engine rust context, then from there we convert in the actor for anything that uses `LengthUnit` the wrapper around an f64. 

Open to other names I don't really care but yeah this is what we landed on last week as for the implementation

TODO:
- [ ] make sure we change every f64 that needs to be changed to the new type
- [ ] add `SetUnits` modeling cmd
- [ ] pull thru to engine and make sure it all works

2024-02-19 04:21 UTC, jessfraz commented
added all the reviewers to make sure I didn't miss an endpoint that needs updating or that i didn't update something that is not actually a unit

2024-02-19 10:03 UTC, alteous commented on modeling-cmds/src/length_unit.rs
> +            w: self.w.to_millimeters(from),
The `w` component should be left as-is.

2024-02-19 18:37 UTC, jessfraz commented on modeling-cmds/src/length_unit.rs
> +            w: self.w.to_millimeters(from),
good find

2024-02-20 17:03 UTC, adamchalmers requested changes

2024-02-20 17:03 UTC, adamchalmers commented on modeling-cmds/src/each_cmd.rs
> +    /// The unit to interpret the scene as.
```suggestion
    /// Which units the scene uses.
```

2024-02-20 17:07 UTC, jessfraz commented on Cargo.lock
was unintentional

2024-02-20 17:47 UTC, adamchalmers approved these changes

2024-02-20 18:39 UTC, merged