Extend the cube_png_batch example to stress test batch
KittyCAD/modeling-api pull request #220
Opened 2024-03-15 13:57 UTC by lf94

2024-03-15 18:25 UTC, adamchalmers requested changes

2024-03-15 18:25 UTC, adamchalmers commented on modeling-session/examples/lsystem_png_batch.rs
> +//! Use the KittyCAD modeling API to draw a cube and save it to a PNG.
not a cube :)

2024-03-15 18:25 UTC, adamchalmers commented on modeling-session/examples/lsystem_png_batch.rs
> +    let img_output_path = env::var("IMAGE_OUTPUT_PATH").unwrap_or_else(|_| "model_batched.png".to_owned());
please use a different path from the other batch example

2024-03-18 13:10 UTC, lf94 commented
@adamchalmers Addressed

2024-03-19 16:59 UTC, adamchalmers approved these changes

2024-03-19 17:03 UTC, merged